---
title: "Tìm kiếm và quản lý tài liệu tham khảo"
author: "BS. Kim Văn Thành"
date: "24/09/2020"
output:
  beamer_presentation:
    highlight: null
    latex_engine: xelatex
    slide_level: 2
    theme: Hannover
  slidy_presentation:
institute: Bộ môn Dịch tễ học - Đại học Y khoa Phạm Ngọc Thạch
titlegraphic: YTCC.CoatofArms
---
## Mục tiêu bài học

1. Trình bày lý do tại sao cần quản lý và trích dẫn tài liệu tham khảo.  

2. Xác định được nội dung cần và không cần trích dẫn.  

3. Thực hiện được kĩ năng quản lý tài liệu tham khảo với EndNote X8.  

4. Thao tác được kĩ năng trích dẫn tài liệu vào văn bản với EndNote X8.  

## Tầm quan trọng của tài liệu tham khảo

- Làm nền tảng của tổng quan y văn

- Cụ thể hóa câu hỏi và phương pháp nghiên cứu

- So sánh, bàn luận với kết quả tìm kiếm được

## Tại sao phải quản lý tài liệu tham khảo

- Càng nhiều tài liệu tham khảo.  

- Tiếp cận nguồn tài nguyên khi cần.  

- Tìm kiếm, truy xuất tài liệu hiệu quả.  

## Lý do cần trích dẫn tài liệu tham khảo

* Tránh việc đạo văn, công nhận công sức của tác giả.  

* Cho thấy nền tảng kiến thức vững chắc của nghiên cứu.  

* Trình bày nguồn tham khảo cho người đọc với đúng ấn bản.  

* Cho phép bản thân và người đọc kiểm chứng chất lượng thông tin.  

## Khi nào cần trích dẫn?

  - Trích dẫn trực tiếp từ một nguồn.  
  
  - Diễn giải một nguồn theo từ ngữ của mình.
  
  - Tóm tắt ý tưởng của người khác.
  
  - Trình bày thông tin, sự thật, hoặc dữ liệu từ một nguồn.
  
## Khi nào không cần trích dẫn

  - Đưa ra những suy nghĩ, quan điểm, hoặc suy luận của mình. 
  
  - Trình bày kiến thức phổ quát. 

## Nguyên tắc chung

  __"Khi cảm thấy nghi ngờ, hãy trích dẫn"__

## Phần mềm EndNote

Hệ thống quản lý tài liệu tham khảo

- Cơ sở dữ liệu/Thư viện.  
  * PubMed, Web of Science  
  * Tập tin lưu trữ  

- Một bản ghi TLTK chứa được tới 45 đính kèm. 

- Việc tìm kiếm TLTK với toán tử Boolean (AND, OR, NOT).  

- `Import` TLTK thay vì phải nhập tay.

- Trích dẫn nhanh, gọn với công cụ `Trích dẫn khi đang viết`

- Linh động thay đổi phong cách trình bày tương ứng với 6,000 tạp chí khoa học.  

- Hoạt động trên Windows, iOS, trực tuyến. 





